spring:
  application:
    name: pos-api-gateway

  cloud:
    gateway:
      routes:
        - id: pos-order-service
          uri: http://order-service:8081
          predicates:
            - Path=/api/orders/**
        - id: pos-inventory-service
          uri: http://inventory-service:8082
          predicates:
            - Path=/api/inventory/**
