server:
  port: 8080

spring:
  application:
    name: pos-api-gateway

  cloud:
    gateway:
      routes:
        - id: pos-order-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/orders/**
        - id: pos-inventory-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/inventory/**
